"""
Executive Report Builder Module
Compiles datasets, Data Health scores, executive AI summaries, anomalies, and Plotly charts into HTML reports.
"""

import datetime
from database.connection import run_query
from ai.data_health_engine import analyze_table_health
from ai.anomaly_engine import detect_dataset_anomalies
from ai.prediction_engine import generate_dataset_forecast


def generate_executive_report_html(table_name: str, company_name: str = "Enterprise Analytics Corp", user_email: str = "") -> str:
    """
    Generates a full HTML Executive Analytical Report.
    """
    health = analyze_table_health(table_name)
    anomalies = detect_dataset_anomalies(table_name)
    forecast = generate_dataset_forecast(table_name)

    sample_df = run_query(f"SELECT TOP 10 * FROM [{table_name}]")
    cols = sample_df.columns.tolist() if sample_df is not None else []
    rows_html = ""
    if sample_df is not None and not sample_df.empty:
        head_ths = "".join([f"<th style='padding: 10px; border-bottom: 2px solid #2563eb; background: #f8fafc;'>{c}</th>" for c in cols[:8]])
        tbody_trs = []
        for _, r in sample_df.head(5).iterrows():
            tds = "".join([f"<td style='padding: 8px; border-bottom: 1px solid #e2e8f0;'>{str(r[c])[:30]}</td>" for c in cols[:8]])
            tbody_trs.append(f"<tr>{tds}</tr>")
        rows_html = f"<table style='width:100%; border-collapse:collapse; font-size:12px;'><thead><tr>{head_ths}</tr></thead><tbody>{''.join(tbody_trs)}</tbody></table>"

    anomalies_html = ""
    for a in anomalies[:3]:
        anomalies_html += f"""
        <div style="background: #fef2f2; border-left: 4px solid #ef4444; padding: 12px; margin-bottom: 8px; border-radius: 4px;">
            <strong style="color: #dc2626;">[{a['severity']}] {a['type']}</strong>: {a['what']}<br>
            <small style="color: #475569;">{a['why']} — <em>{a['recommendation']}</em></small>
        </div>
        """
    if not anomalies_html:
        anomalies_html = "<div style='color: #10b981; font-weight: 700;'>✅ No high-severity data anomalies detected.</div>"

    forecast_html = ""
    if forecast.get("success"):
        forecast_items = "".join([f"<li><strong>{item['period']}</strong>: {item['predicted']} (Range: {item['lower_bound']} - {item['upper_bound']})</li>" for item in forecast.get("forecast", [])])
        forecast_html = f"<ul>{forecast_items}</ul><small style='color: #64748b;'>{forecast.get('disclaimer')}</small>"
    else:
        forecast_html = f"<p style='color: #64748b;'>{forecast.get('disclaimer')}</p>"

    report_html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Executive AI Briefing — {table_name}</title>
    <style>
        body {{ font-family: 'Inter', system-ui, sans-serif; color: #0f172a; margin: 0; padding: 30px; background: #f8fafc; }}
        .report-card {{ background: #ffffff; padding: 30px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.08); max-width: 900px; margin: 0 auto; }}
        .header {{ border-bottom: 2px solid #e2e8f0; padding-bottom: 16px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: center; }}
        .health-badge {{ font-size: 24px; font-weight: 800; color: #2563eb; background: #eff6ff; padding: 10px 20px; border-radius: 8px; border: 1px solid #bfdbfe; inline-block; }}
        .section-title {{ font-size: 18px; font-weight: 800; color: #1e293b; border-left: 4px solid #2563eb; padding-left: 10px; margin: 24px 0 12px 0; }}
    </style>
</head>
<body>
    <div class="report-card">
        <div class="header">
            <div>
                <h1 style="margin: 0; font-size: 24px; color: #1e293b;">{company_name}</h1>
                <p style="margin: 4px 0 0 0; color: #64748b; font-size: 13px;">Executive AI Briefing & Quality Audit | Date: {datetime.datetime.now().strftime('%B %d, %Y')}</p>
            </div>
            <div class="health-badge">
                Health Score: {health['score']}/100 ({health['rating']})
            </div>
        </div>

        <div class="section-title">📊 Dataset Quality & Hygiene Summary</div>
        <p>Total Rows: <strong>{health['total_rows']:,}</strong> | Total Columns: <strong>{health['total_columns']}</strong> | Missing Cells: <strong>{health['null_percentage']}%</strong> | Duplicates: <strong>{health['duplicate_percentage']}%</strong></p>

        <div class="section-title">⚠️ Risk & Anomaly Alerts</div>
        {anomalies_html}

        <div class="section-title">📈 30-90 Day Predictive Trend Forecast</div>
        {forecast_html}

        <div class="section-title">📋 Dataset Sample Preview</div>
        {rows_html}

        <div style="margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 16px; font-size: 11px; color: #94a3b8; text-align: center;">
            Generated by AI Data Analyst Pro Engine for {user_email or 'Executive Stakeholders'}
        </div>
    </div>
</body>
</html>"""

    return report_html
