"""
Scheduled Briefing & Threshold Alert Service
Manages automated email report schedules and KPI alert delivery using EmailService.
"""

from auth.email_service import EmailService
from utils.report_builder import generate_executive_report_html

_email_service = EmailService()


def send_scheduled_executive_briefing(to_email: str, table_name: str, schedule_type: str = "Daily") -> bool:
    """
    Generates and dispatches executive HTML briefing report to user's registered email.
    """
    try:
        report_html = generate_executive_report_html(table_name, user_email=to_email)
        subject = f"📊 [{schedule_type} Briefing] AI Executive Analytics Report: {table_name}"
        return _email_service._send_email_async(to_email, subject, report_html)
    except Exception:
        return False


def dispatch_kpi_threshold_alert(to_email: str, alert_title: str, message: str) -> bool:
    """
    Dispatches immediate high-priority KPI threshold alert email.
    """
    subject = f"🚨 [ALERT] {alert_title} - AI Data Analyst Pro"
    html_body = f"""
    <div style="font-family: Arial, sans-serif; padding: 20px; background: #fff1f2; border-left: 4px solid #e11d48; border-radius: 6px;">
        <h3 style="color: #be123c; margin-top: 0;">🚨 High Priority KPI Threshold Alert</h3>
        <p><strong>Alert Event:</strong> {alert_title}</p>
        <p><strong>Details:</strong> {message}</p>
        <hr style="border: 0; border-top: 1px solid #fecdd3;">
        <small style="color: #9f1239;">Generated by AI Data Analyst Pro Real-time Alert System</small>
    </div>
    """
    return _email_service._send_email_async(to_email, subject, html_body)
